accounts/urls.py
from django.urls import path,include
from accounts import views
from django.contrib.auth import views as auth_views
from .forms import CustomAuthentictaionForm
from django.http import request


app_name = 'accounts'

urlpatterns = [
    path('login/',views.Login.as_view(),name='login'),
    path('signup/',views.SignUp.as_view(),name='register'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('profile/',views.Profile.as_view(),name='profile'),
    path('<pk>/delete/',views.del_user,name='delete')
    
]

mtra_pro/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexPage.as_view(),name='home'),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/notifications/',include('notifications_app.urls',namespace='notification')),
    path('inbox/notifications/',include(notifications.urls,namespace='notifications')),
    path('posts/',include('posts.urls',namespace='posts')),
    path('email-subscription/',views.EmailSubscriptions,name='email_subscription'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path,re_path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('',views.Blog_PostListView.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    re_path(r'^details/(?P<pk>\d+)/$',views.Blog_PostDetail.as_view(),name='post_det'),
    path('delete/<pk>',views.DeletePost.as_view(),name='delete'),
    
]

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,AuthenticationForm
from django.forms import ModelForm
from accounts.models import Education_level, Employment_detail, File_uploaded, Preference, Subscribers, User
from django.contrib.auth import get_user_model
from django import forms

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ('email',)
        
class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm):
        model = User
        fields = ('email',)  
class CustomAuthentictaionForm(AuthenticationForm):
    username = forms.CharField(widget= forms.EmailInput(attrs={'class':'field_input','placeholder':'Email e.g(you@example.com)','required':True,'autofocus':True}))
    password = forms.CharField(widget= forms.PasswordInput(attrs={'class':'field_input','placeholder':'password','required':True}))
   
   
             
class UserCreateForm(CustomUserCreationForm):
    username = forms.CharField(widget= forms.TextInput(attrs={'placeholder':'user name','class':'field_input','required':True,'autofocus':True}),error_messages={'required':'Note username should be unique!'})
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'Email(e.g you@example.com)','class':'field_input','required':True}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'phone','class':'field_input','required':True}))
    password1 = forms.CharField(widget= forms.PasswordInput(attrs={'class':'field_input','placeholder':'password','required':True}))
    password2 = forms.CharField(widget= forms.PasswordInput(attrs={'class':'field_input','placeholder':'confirm password','required':True}))
   
   
    class Meta:
        fields = ('username','email','phone','password1','password2')
        model = get_user_model()
class UserProfileForm(ModelForm):
    
    username = forms.CharField(widget= forms.TextInput(attrs={'placeholder':'user name','class':'form-ctrl','required':True,'autofocus':True}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'first name','class':'form-ctrl','required':True}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'last name','class':'form-ctrl','required':True}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'Email(e.g you@example.com)','class':'form-ctrl','required':True}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'phone','class':'form-ctrl','required':True}))
    address = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'address','class':'form-ctrl','required':True}))
    location = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'location','class':'form-ctrl','required':True}))
    class Meta(UserCreateForm):
        model = get_user_model()
        fields = ('username','first_name','last_name','email','phone','location')
        # ('username','first_name','last_name','email','phone','location')

        excludes = ['password1','password2']
       
   
               
        
class Education_levelForm(ModelForm):
    class Meta:
        model = Education_level
        fields = ('certification','issuing_org','identification_number','issue_date','expiration_date')
        widgets = {
            'certification':forms.TextInput(attrs={'class':'form-ctrl'}),
            'issuing_org':forms.TextInput(attrs={'class':'form-ctrl'}),
            'identification_number':forms.TextInput(attrs={'class':'form-ctrl'}),
            'issue_date':forms.DateTimeInput(attrs={'class':'form-ctrl'}),
            'expiration_date':forms.DateTimeInput(attrs={'class':'form-ctrl'}),
               
        }

class Employement_DetailForm(ModelForm):
    class Meta:
        model = Employment_detail
        fields = ('employer','job_function','current_job_status','start_date','end_date')
        widgets = {
            'employer':forms.TextInput(attrs={'class':'form-ctrl'}),
            'job_function':forms.TextInput(attrs={'class':'form-ctrl'}),
            'current_job_status':forms.Select(attrs={'class':'form-ctrl'},choices=Employment_detail.JOB_STATUS),
            'start_date':forms.DateTimeInput(attrs={'class':'form-ctrl'}),
            'end_date':forms.DateTimeInput(attrs={'class':'form-ctrl'}),
                  
        }


class Preference_Form(ModelForm):
    class Meta:
        model = Preference
        fields = ('job_field_pref','location_pref')
        widgets = {
            'job_field_pref':forms.TextInput(attrs={'class':'form-ctrl'}),
            'location_pref':forms.TextInput(attrs={'class':'form-ctrl'}),
        }
class File_UploadForm(ModelForm):

    class Meta:
        model = File_uploaded
        fields = ('file_name','file','submitted_date','comments')
        widgets = {
            'file_name':forms.TextInput(attrs={'class':'form-ctrl'}),
            'file':forms.FileInput(attrs={'class':'form-ctrl'}),
            'submitted_date':forms.DateTimeInput(attrs={'class':'form-ctrl'}),
            'comments':forms.Textarea(attrs={'class':'form-ctrl' ,'rows':'2'}),
            
        }
             
        
class EmailSubscriptionForm(ModelForm):
    class Meta:
        model = Subscribers
        fields ='__all__'  
        widgets = {
            'email':forms.EmailInput(attrs={'placeholder':'Email(e.g you@example.com)','class':'grid-8 grid-md-5 input_text bg-primaryVeryLight','required':True,'maxlength':'200','title':'Email address'})
            
        }   

accounts/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse,reverse_lazy
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirect, JsonResponse
from django.core import serializers
from accounts.models import Education_level, Employment_detail, File_uploaded, Preference, User
from django.views.generic import (TemplateView,CreateView,DetailView,ListView,View,UpdateView,DeleteView)
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts import forms
from accounts.forms import Education_levelForm, Employement_DetailForm, File_UploadForm, Preference_Form, UserProfileForm
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync

from django.utils import timezone
from django.utils.datetime_safe import datetime
from django.http import HttpResponseForbidden
from django.contrib import messages
from notifications.signals import notify
User = get_user_model()

# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signUp.html'
    
    # def form_valid(self,form):
    #     user = form.save()
    #     # Trigger message sent to group
    #     channel_layer = get_channel_layer()
    #     data = "notification"+ ".New user "+user.username+" has joined @ -." + str(datetime.now())
    #     async_to_sync(channel_layer.group_send)(
    #         "user_notifier",  # Group Name, Should always be string
    #         {
    #             "type": "new_userNotifier",   # Custom Function written in the consumers.py
    #             "event":"New User",
    #             "text": data,
    #         },
    #     ) 
    #     return super(CreateView,self).form_valid(form)   
        
class Login(LoginView):
    authentication_form = forms.CustomAuthentictaionForm
    form_class = forms.CustomAuthentictaionForm
    template_name = 'accounts/login.html'

    
    def form_valid(self, form):
        login(self.request,form.get_user())
        
        return super(LoginView,self).form_valid(form)
    
class Profile(LoginRequiredMixin,FormMixin , View):
    model = User
    template_name = 'accounts/profile.html'
    form = None
    
    def get_queryset(self):
        if self.request.user.is_authenticated:
            return User.objects.filter(user=self.request.user)
        else:
            return User.objects.none()
    def get_object(self, queryset=None):
        return get_object_or_404(get_user_model(),id = self.request.user.id) 
       
   
    def get_context_data(self, **kwargs):
        context = {}
        
        try:
            context['emp_info'] = Employment_detail.objects.none()
        except :
            context['emp_info'] = UserProfileForm()
        try:
            context['profile_form'] = UserProfileForm(instance = self.get_object())
        except :
            context['profile_form'] = UserProfileForm()
        try:
            context['edu_detailform'] = Education_levelForm(instance=Education_level.objects.filter(user=self.request.user).first())
        except :
            context['edu_detailform'] = Education_levelForm()
        try:
            context['emp_detailform'] = Employement_DetailForm(instance=Employment_detail.objects.all().filter(user=self.request.user).first())
        except :
            context['emp_detailform'] = Employement_DetailForm()
        try:
            context['pref_form'] = Preference_Form(instance=Preference.objects.filter(user=self.request.user).first())
        except :
            context['pref_form'] = Preference_Form()         
        try:
            context['file_uploadform'] = File_UploadForm(instance=File_uploaded.objects.filter(user=self.request.user).first())
        except :
            context['file_uploadform'] = File_UploadForm()  
        
        return context 
    def get(self, request, *args, **kwargs):
        return render(self.request, self.template_name,self.get_context_data())
    def post(self, request, *args, **kwargs):
        if self.request.is_ajax and self.request.method == "POST":
            if 'edu_details' in request.POST:
                #get profile form
                try:
                    form = Education_levelForm(self.request.POST,instance=Education_level.objects.filter(user=self.request.user).first())
                except:
                    form = Education_levelForm(self.request.POST)
                
            elif 'emp_details' in request.POST:
                try:
                    form = Employement_DetailForm(self.request.POST,instance=Employment_detail.objects.filter(user=self.request.user).first())
                except:
                    form = Employement_DetailForm(self.request.POST)
            elif 'pref_info' in request.POST:
                try:
                    form = Preference_Form(self.request.POST,instance=Preference.objects.filter(user=self.request.user).first())
                except:
                    form = Preference_Form(self.request.POST)
            elif 'file_upload' in request.POST:
                try:
                    form = File_UploadForm(self.request.POST,self.request.FILE,instance=File_uploaded.objects.filter(user=self.request.user).first())
                except:
                    form = File_UploadForm(self.request.POST)
            else:
                form = UserProfileForm(self.request.POST,instance=self.get_object())
                              
            if form.is_valid():
                instance = form.save(commit = False)
                instance.user = self.get_object()
                instance.save()
                # invoke websocket- send data to client
                current_user = request.user # Getting current user
                channel_layer = get_channel_layer()
                data = "notification"+ "..added some details.." + str(timezone.now()) # Pass any data based on your requirement
                # Trigger message sent to group
                async_to_sync(channel_layer.group_send)(
                    str(current_user.pk),  # Group Name, Should always be string
                    {
                        "type": "notify",   # Custom Function written in the consumers.py
                        "text": data,
                    },
                )
                notify.send(self.get_object(),recipient=self.get_object(), verb="notification  :"+ "your profile succesful updated @ " +str(datetime.now()) )
                
                
                #send to client side
                return JsonResponse({"message":"Your details submmitted & proccessed succeful","user":serializers.serialize('json',[instance,])},status=200)
            else:
                return JsonResponse({"errors":form.errors},status=400)
        return JsonResponse({"errors":""},status=400)    
        
class UserDeleteView(DeleteView):
    model = get_user_model()
    success_url = '/'
    template_name = None
    def delete(self, request, *args,**kwargs):
        self.object = self.get_object()
        if request.is_ajax():
            print("Ajax request in delete")
        
            if self.object.User == request.user:
                success_url = self.get_success_url()
                self.object.delete();
                HttpResponseRedirect(success_url)
                
                return JsonResponse({"message":"You have deleted your account"},status=200)
            else:
                HttpResponseForbidden("Cannot delete the user")
                
                return JsonResponse({"errors":""},status=400) 
            
def del_user(request,pk):
    if request.is_ajax():
        print("Ajax request in delete")
        try:
            user = User.objects.get(pk = pk)
            success_url = '/'
            user.delete()
            messages.success(request,'The user is deleted')
            HttpResponseRedirect(success_url)        
            return JsonResponse({"message":"You have deleted your account"},status=200)
            
        except User.DoesNotExist:
            return JsonResponse({"errors":"User does not exist"},status=400) 
        except Exception as e:
            return JsonResponse({"errors":str(e.message)},status=400)
        
                

accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login | MT&RA</title>
    <link rel="icon" href=" {% static 'images/logo.svg' %} " type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'css/login.css' %} " />
    <link rel="stylesheet" href="{% static 'css/fontawesome-free-5.2.0-web/css/all.css' %} " />
</head>

<body class="bg_dark">
    <div class=""></div>
    <main class="full-view">
        <section class="full-view_inner_cont">
            <form method="post" action="" class="login" id="login">
              {% csrf_token %}
                <article class="login-desc">
                    <span class="fas fa-user-tie" style="color: #fff;font-size: 3rem;"></span>
                    <p>User login</p>
                </article>
                {% if form.errors %}
                  <ol>
                    {% for error in form.errors %}
                      <li><strong>{{ error|safe }}</strong></li>
                    {% endfor %}
                  </ol>
                {% endif %}
                <article class="login_field field">
                    {% if form.username.errors %}<li>{{form.username.errors|striptags}}</li>{% endif %}
                    <span class="fas fa-user-clock field_icon"></span>
                     {{form.username}}   
                </article>
                <article class="login_field field">
                    {% if form.password.errors %}<li>{{form.password.errors|striptags}}</li>{% endif %}
                    <span class="fas fa-eye-slash field_icon"></span>
                    {{form.password}}  
                </article>
                <article class="login_row">
                    <a href="{% url 'password_reset' %}" class="login_forgot">Forgot password</a>
                </article>
                <article class="login_footer">
                    <button type="submit" class="login_btn">Login</button>
                </article>
            </form>
        </section>
        <footer class="full-view_footer">
            <div class="full-view_quiz">
                Don't have an account?
                <a href="{% url 'accounts:register' %}">sign Up</a>
            </div>
        </footer>
    </main>
    <div class="fs_loader">
        <div class="loader"></div>
    </div>
</body>
{% comment %} <script>
    document.querySelector(".login_btn").addEventListener("click", function(e) {
        e.preventDefault();
        window.location = "{% url 'accounts:profile' %}";
    });
</script> {% endcomment %}

</html>

accounts/templates/accounts/notifier.html
{% extends 'accounts/profile_base.html' %}
{% load notifications_tags %}
{% load static %}

{% block main_content %}
    <section class="">
        <h4>user notifications</h4>
        <p>Your currently have <span>{% notifications_unread %}</span> notifications</p>
        
        {% live_notify_list %}
    
    </section>

{% endblock main_content %}

accounts/templates/accounts/signUp.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sign Up | MT&RA</title>
    <link rel="icon" href=" {% static 'images/logo.svg' %} " type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'css/signUp.css' %} " />
    <link rel="stylesheet" href="{% static 'css/fontawesome-free-5.2.0-web/css/all.css' %} " />
</head>

<body class="body-dark_bg">
    <div class=""></div>
    <main class="fullscreen">
        <section class="fullscreen-inner_cont">
            <form action="" method="POST" class="sign-up" id="sign-up_form">
                {% csrf_token %}
                <a href="{% url 'home' %}" style="color: #fff;text-decoration: none;">
                    <img src=" {% static 'images/logo.svg' %} " alt="" style="width: 68px; height: 68px; border-radius: 50%;" /> MT&RA
                </a>
                <div class="sign-up_desc">
                    <p>Please fill out the information below</p>
                    <span class="fas fa-user-circle" style="color: #fff;font-size: 3rem;"></span>
                </div>
                {% if form.errors %}
                  <ol>
                    {% for error in form.errors %}
                      <li><strong>{{ error|escape }}</strong></li>
                    {% endfor %}
                  </ol>
                {% endif %}
                <article class="sign-up_field field field_with-icon">
                    <span class="fas fa-user-check field_icon"></span>
                     {{form.username}}
                </article>
                <article class="sign-up_field field field_with-icon">
                    <span class="fas fa-envelope-open field_icon"></span>
                     {{form.email}}
                </article>
                <article class="sign-up_field field field_with-icon">
                    <span class="fas fa-phone field_icon"></span>
                     {{form.phone}}
                </article>
                <article class="sign-up_field field field_with-icon">
                    <span class="fas fa-eye-slash field_icon"></span>
                    {{form.password1}}
                </article>
                <article class="sign-up_field field field_with-icon">
                    <span class="fas fa-eye-slash field_icon"></span>
                    {{form.password2}}
                </article>
                <article class="sign-up_footer">
                    <button type="submit" class="sign-up_btn">Continue</button>
                </article>
            </form>
        </section>
        <footer class="full-view_footer">
            <div class="full-view_quiz">
                Already have an account?
                <a href=" {% url 'accounts:login' %}">Login</a>
            </div>
            <div class="notice">
                <p>
                    By clicking&nbsp;continue,&nbsp;i agree to pro-job
                    <a href=""> Terms and conditions</a>,<a href="">Privacy&nbsp;policy</a> and <a href="">Refund&nbsp;Policy</a>
                </p>
            </div>
        </footer>
    </main>
</body>

</html>